### ISSUE TITLE
Provisioning.SubSiteCreationApp - Access Denied

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP#1029]
Hi,

I'm trying to get myself familiar with the PNP Provisioning Apps. I'm looking at the Provisioning.SubSiteCreationApp  sample. I saw Vesa doing a demo of this in the London SharePoint conference and this looks very promising.

I've got a Office 365 dev site and I've deployed the app. The app deploys to my Office 365 site without any errors. 

I'm running the Debugger from my Visual Studio. I'm getting the site creation form. I complete the new site details and click on the create button:

and the AddJsLink gives me an access denied on the  last ctx.ExecuteQuery();

Microsoft.SharePoint.Client.ServerUnauthorizedAccessException was unhandled by user code
  HResult=-2146233088
  Message=Access denied. You do not have permission to perform this action or access this resource.
  Source=Microsoft.SharePoint.Client.Runtime
  ServerErrorCode=-2147024891
  ServerErrorTraceCorrelationId=f401189d-602d-2000-09b5-4141fe49fb3f
  ServerErrorTypeName=System.UnauthorizedAccessException
  ServerStackTrace=""
  StackTrace:
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
       at Contoso.Provisioning.SubSiteCreationAppWeb.LabHelper.AddJsLink(ClientContext ctx, Web web, HttpRequest request) in c:\Projects\PnP-master\PnP-master\Samples\Provisioning.SubSiteCreationApp\Provisioning.SubSiteCreationAppWeb\LabHelper.cs:line 119
       at Contoso.Provisioning.SubSiteCreationAppWeb.Default.CreateSubSite(ClientContext ctx, Web hostWeb, String txtUrl, String template, String title, String description) in c:\Projects\PnP-master\PnP-master\Samples\Provisioning.SubSiteCreationApp\Provisioning.SubSiteCreationAppWeb\Pages\Default.aspx.cs:line 95
       at Contoso.Provisioning.SubSiteCreationAppWeb.Default.btnCreate_Click(Object sender, EventArgs e) in c:\Projects\PnP-master\PnP-master\Samples\Provisioning.SubSiteCreationApp\Provisioning.SubSiteCreationAppWeb\Pages\Default.aspx.cs:line 68
       at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
       at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
       at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
       at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
       at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException: 

The odd thing is that my sub site is created. So obviously the app has the right permissions to create the sub site.

My appManifest shows that the app has Full control on the Site Collection (this is the default setting anyway)

any idea what I'm doing wrong?

**Comment by braegelno5** [comment]
I think you run the web project on localhost from vs the normal way like Vesa in an video..
Please check with fiddler if there are any anomalies are shown in the communication flow.

**Comment by ParthasarathyBalan** [comment]
Hi PieterVeenstra,
                           I am also facing the same problem now. May i know what was the fix for that issue?
