### ISSUE TITLE
Get-SPOProvisioningTemplate - not working

### ISSUE THREAD

**Issue by aboredman** [OfficeDev/PnP#1287]
Hello,

I am trying to use Get-SPOProvisioningTemplate but keep getting an error:

Connect-SPOnline https://abcdef.sharepoint.com/sites/prov_source -Credentials $cred
Get-SPOProvisioningTemplate -Out template.xml

Get-SPOProvisioningTemplate : Specified argument was out of the range of valid values.
Parameter name: controlId
At line:1 char:1
+ Get-SPOProvisioningTemplate -Out template.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate

The command runs ok for a while but it seems to crash when extracting the Page contents.

My site is pretty simple, a brand new team site with a few site columns and content types. Only home page with the documents library webpart on it.

Similar post: https://github.com/OfficeDev/PnP/issues/1127

Any idea?

**Comment by erwinvanhunen** [comment]
Directly after you receive the error, in PowerShell, can you enter

```powershell
$error[0].Exception.Stacktrace
```

and post the result of that command? Thanks!

**Comment by aboredman** [comment]
PS C:\Users\Robert> $error[0].Exception.Stacktrace
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext
, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPageContents.ExtractObjects(Web web, ProvisioningTe
mplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, Provi
sioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate.GetProvisioningTemplateXML(XMLPnPSchemaVersion
schema, String path)
   at OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate.ExecuteCmdlet()
   at OfficeDevPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()

**Comment by aboredman** [comment]
I managed to make it work... not 100% sure why.

I decided to debug the code in OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPageContents so I forked it and started debugging with VS attached to powershell.exe

At the same time I edited my wikipage (homepage) on the site to add a bit of content.

As I started debugging, it worked on the first try, no error or anything... My guess is that either the page was messed up and it fixed itself when I added some content (I love SharePoint RTE) or I had an older version of the code library code in memory and it caused some error?

Hope it helps someone

**Comment by CedricOettel** [comment]
Hi, i have had the same issue on Wiki Pages. As @aboredman stated, if you clean the wiki field value from "old" Webpart Id's it works.

In my case i have had a default Teamsite (O365) and removed the microfeed and document library webpart's.
After that the wikiField Content still had this Markup:
```
<div class="ms-rtestate-read ms-rte-wpbox" contenteditable="false">
   <div class="ms-rtestate-notify  ms-rtestate-read b555aff4-e661-4242-9ada-016f6febd1c2" id="div_b555aff4-e661-4242-9ada-016f6febd1c2" unselectable="on">
   </div> 
   <div class="ms-rtestate-read" id="vid_b555aff4-e661-4242-9ada-016f6febd1c2" unselectable="on" style="display: none;">
   </div> 
</div> 
<div class="ms-rtestate-read ms-rte-wpbox" contenteditable="false">
   <div class="ms-rtestate-notify  ms-rtestate-read 89be1e31-50bb-4be0-952f-cbc1cca44ac3" id="div_89be1e31-50bb-4be0-952f-cbc1cca44ac3">
   </div>
   <div id="vid_89be1e31-50bb-4be0-952f-cbc1cca44ac3" style="display: none;">
   </div>
</div>

```
After removing this Markup with Ribbon Action "Edit Source", i could get the ProvisioningTemplate with -Handlers Pages, PageContents

**Comment by aboredman** [comment]
Thanks Cedric. I managed to replicate the issue and correct it using your method.

**Comment by JMauricioGR** [comment]
Hi, I have had the same issue but my error result was different:

   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retry
Count, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectTermGroups.CreateTerm[T](Web web, Term modelTerm, TaxonomyItem p
arent, TermStore termStore, TokenParser parser, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectTermGroups.ProvisionObjects(Web web, ProvisioningTemplate templa
te, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemp
late template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()

I try implement a remote provisioning site.

Thanks for all support
