### ISSUE TITLE
Feature not installed in SharePoint Online

### ISSUE THREAD

**Issue by statto1974** [OfficeDev/PnP#1295]
I get the following error when running this.

Feature with Id '29deab23-c821-460e-822f-790eb7ff3cea' is not installed in this farm, and cannot be added to this scope.

Obviously as this is SharePoint Online we have no custom solutions or features. This was also running between to sub-sites in the same site collection.

Full stack trace below

Microsoft.SharePoint.Client.ServerException was unhandled
  HResult=-2146233088
  Message=Feature with Id '29deab23-c821-460e-822f-790eb7ff3cea' is not installed in this farm, and cannot be added to this scope.
  ServerErrorCode=-1
  ServerErrorTraceCorrelationId=0604599d-50de-2000-09c1-44c7fdfd38b4
  ServerErrorTypeName=System.InvalidOperationException
  ServerStackTrace=""
  Source=Microsoft.SharePoint.Client.Runtime
  StackTrace:
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
       at Microsoft.SharePoint.Client.FeatureExtensions.ProcessFeatureInternal(FeatureCollection features, Guid featureID, Boolean activate, FeatureDefinitionScope scope)
       at Microsoft.SharePoint.Client.FeatureExtensions.ActivateFeature(Web web, Guid featureID, Boolean sandboxed)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectFeatures.ProvisionFeaturesImplementation[T](T parent, List`1 features)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectFeatures.ProvisionObjects(Web web, ProvisioningTemplate template)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
       at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
       at Provisioning.Framework.Program.ApplyProvisioningTemplate(ConsoleColor defaultForeground, String webUrl, String userName, SecureString pwd, ProvisioningTemplate template) in C:\Users\toby\Source\Repos\PnP\Samples\Provisioning.Framework.Console\Provisioning.Framework.Console\Program.cs:line 128
       at Provisioning.Framework.Program.Main(String[] args) in C:\Users\toby\Source\Repos\PnP\Samples\Provisioning.Framework.Console\Provisioning.Framework.Console\Program.cs:line 36
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by VesaJuvonen** [comment]
Thanks @statto1974 for reporting this. It seems that there has been a momentary time when sites have been associated a oob feature, which no longer exists in the farm. This could be due numerous reasons, but engine should not actually break on this situation. 

This means that we'll adjust the code for the Feb 2016 release to gracefully handle possible missing feature exceptions and only log that in the logs, but we will not shut down the provisioning.

**Comment by VesaJuvonen** [comment]
Just to follow up on this. Code in the engine has been changed to catch possible missing features, log about those and then move on. This is needed to manage these kind of situations where the feature suddenly has been removed in the farm. Code change is already in the dev branch and will be released as Nuget update as part of the February 2016 release.
