### ISSUE TITLE
Exception in provisionning job - user@domain.com is not a valid user

### ISSUE THREAD

**Issue by AnassKartit** [OfficeDev/PnP#1407]
when creating a site collection, I am receiving the below error it seems it is using email address in userprofile to provision but we have different login ID id@domain.com used for logins..
any ideas?

Exception occurred: user_email@domain.com is not a valid user.
[04/18/2016 10:25:44 > e98a44: INFO] Stack Trace:
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
[04/18/2016 10:25:44 > e98a44: INFO]    at Microsoft.SharePoint.Client.TenantExtensions.CreateSiteCollection(Tenant tenant, SiteEntity properties, Boolean removeFromRecycleBin, Boolean wait)
[04/18/2016 10:25:44 > e98a44: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)
[04/18/2016 10:25:44 > e98a44: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job)
[04/18/2016 10:25:44 > e98a44: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job)
[04/18/2016 10:25:44 > e98a44: INFO] 
[04/18/2016 10:25:44 > e98a44: INFO] Executed: 'Functions.ProcessQueueMessage' (Succeeded)

**Comment by AnassKartit** [comment]
Resolved by changing the code in HomeController as below 

 job.Owner = ClaimsPrincipal.Current.Identity.Name;
                        job.PrimarySiteCollectionAdmin = model.PrimarySiteCollectionAdmin != null &&
                            model.PrimarySiteCollectionAdmin.Length > 0 ? model.PrimarySiteCollectionAdmin[0].Login.Split('|')[2] : null;
                        job.SecondarySiteCollectionAdmin = model.SecondarySiteCollectionAdmin != null &&
                            model.SecondarySiteCollectionAdmin.Length > 0 ? model.SecondarySiteCollectionAdmin[0].Login.Split('|')[2] : null;
