### ISSUE TITLE
Provisioning Breaking Change: TokenParser.Constructor() -Exception: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by TimDaborn2** [OfficeDev/PnP#1461]
#### Which PnP repository 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Not to raise an exception!

#### Observed Behavior

I have encountered an issue in the June release of the Core, when calling _Web.ApplyProvisioningTemplate_ in the constructor of the _TokenParser_, it iterates through the _web.Lists_ of the Subsite I am trying to provision, but it throws an ArgumentOutOfRangeException (startIndex cannot be larger than length of string) on the line:

**_tokens.Add(new ListUrlToken(web, rootList.Title, rootList.RootFolder.ServerRelativeUrl.Substring(web.ServerRelativeUrl.Length + 1)));**

When processing the first item in the list (AppPackages), the Token Parser seems to be expecting to find the Web ServerRelativeUrl within the RootList ServerRelativeUrl , when it isn't, hence the startIndex cannot be larger than length of string

	rootList.RootFolder.ServerRelativeUrl = "/Lists/AppPackages"
	
	web.ServerRelativeUrl = "/Experimental/2000001532"

[PnPProvisioningDemo.xml.txt](https://github.com/OfficeDev/PnP/files/323124/PnPProvisioningDemo.xml.txt)

The same issue applies to the other items in list that I checked.

I had no problems with May release.

#### Steps to Reproduce
I attach the xml (had to denote it as a text file for the uploader.)

 Calling code:

                ProvisioningTemplateApplyingInformation ptai
                        = new ProvisioningTemplateApplyingInformation();
                ptai.ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
                {
                    Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                };

              
                FileSystemConnector connector = new FileSystemConnector(STR_XmlTemplateFilePath, "");
                defaultTemplate.Connector = connector;

               
                web.ApplyProvisioningTemplate(defaultTemplate, ptai);

                ctx.ExecuteQueryRetry();

I am happy to provide any other information, you may need.

Thanks for your help!

**Comment by TimDaborn2** [comment]
Since I wrote this bug report version 2.5.1606.02 has been released on NuGet.   
I now get a different exception: 'The field was found invalid:  {{listid:Documents} {fieldtitle:Modified} {fieldtitle:Modified}.'  Hopefuily somebody is working on a 2.5.1606.03 release.   If nobody is aware of this problem. let me know and I will provide more detail.

**Comment by erwinvanhunen** [comment]
Can you provide a stacktrace of this exception? Preferably also the template you're trying to provision?

**Comment by TimDaborn2** [comment]
Hi Erwin,

Thanks for replying

   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateField(XElement fieldElement, ListInfo listInfo, TokenParser parser, String originalFieldXml, ClientRuntimeContext context, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at MomentusSharePoint.SharePointModel.ManagerSiteServices.ApplyProvisioningTemplate(IManagerInfo manager, ProvisioningTemplate template, Boolean injectHtmlIntoHomePage, Boolean configureSiteColumns) in C:\Perforce\Server\MomentusSharePointServices\SharePointServices\ManagerSiteServices.cs:line 617
   at MomentusSharePoint.SharePointModel.ManagerSiteServices.CreateSiteAndProvision(IManagerInfo manager, List`1 fundsForManager, Boolean removeConflicts, Boolean injectHtmlIntoHomePage, Boolean configureSiteColumns) in C:\Perforce\Server\MomentusSharePointServices\SharePointServices\ManagerSiteServices.cs:line 246
   at IntegrationTestLibrary.ManagerSiteServicesTests.Test_Site_Creation_Creates_Site_For_Real() in C:\Perforce\Server\MomentusSharePointServices\IntegrationTestLibrary\SharePointModel\ManagerSiteServicesTests.cs:line 156

Just to give some context here:

I have a site that I use as a template to provision other sites, called Default.  It is a fairly simple site based on a teamsite with a document library that has 2 columns that are lookups on 2 lists: one which is a list on the site, the other which is  the list on the parent site.  The library has some views mostly based on the 2 columns.  The sites I create end in a numeric, which is a Manager ID and is unique.

Let me know if you require any more info


Tim

[cid:image001.png@01D1CB1A.62D94750]

**Comment by erwinvanhunen** [comment]
Can you extract a template from your 'Default' site and provide me with that template? Just to see what the engine extracts and in which way from your site.

**Comment by TimDaborn2** [comment]
It was attached to the email, but I will upload it here on the site.
[PnPProvisioningDemo.xml.txt](https://github.com/OfficeDev/PnP/files/323914/PnPProvisioningDemo.xml.txt)
A quick note - this should be the raw template, for the May release I had to tweak it to get it how I want, in particular set a string ine th web part and assign a list correctly.  Thanks for your help - any more questions and I will respond tomorrow,  Tim

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#768
