### ISSUE TITLE
Apply Provisioning Template failing at copy Lists

### ISSUE THREAD

**Issue by Kirschi** [OfficeDev/PnP#1528]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Applying a Template to a new Site Collection works.

#### Observed Behavior
An Error is throw in version 2.7.1609.3:

Information: 0 : 2016-09-20 12:53:55.6156      [List instances]        [9]     [Debug] Creating list {res:List_Dokumente_Title} failed: Passing in an empty or null value of parameter 'strTitle' :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance list, TokenParser parser, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation ap

#### Steps to Reproduce
Getting Template from a completely new Site Collection and applying it to a new one with ProvisioningTemplateCreationInformation and ProvisioningTemplateApplyingInformation,  web.ApplyProvisioningTemplate using all Features. The Template SC is a new Team Site with just a few additional Site Groups. It fails at copying the default Documents Library.

[PnPProvisioningDemo.zip](https://github.com/OfficeDev/PnP/files/482399/PnPProvisioningDemo.zip)

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#766

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#767
